
EPSILON = 1e-2
STREET_SEGMENT_LENGTH = 300
HIGHWAY_SEGMENT_LENGTH = 400
STREET_SEGMENT_WIDTH = 6
HIGHWAY_SEGMENT_WIDTH = 16
STREET_BRANCH_PROBABILITY = 0.4
HIGHWAY_BRANCH_PROBABILITY = 0.05

HIGHWAY_BRANCH_POPULATION_THRESHOLD = 0.1
NORMAL_BRANCH_POPULATION_THRESHOLD = 0.1
NORMAL_BRANCH_TIME_DELAY_FROM_HIGHWAY = 5
NORMAL_BRANCH_TIME_DELAY_FROM_STREET = 0
MINIMUM_INTERSECTION_DEVIATION = 30 # degrees
SEGMENT_COUNT_LIMIT = 200
DEBUG_DELAY = 0 # ms
ROAD_SNAP_DISTANCE = 50
HEAT_MAP_PIXEL_DIM = 50 # px

QUADTREE_PARAMS_X = -20000
QUADTREE_PARAMS_Y = -20000
QUADTREE_PARAMS_W = -40000
QUADTREE_PARAMS_H = -40000

QUADTREE_MAX_OBJECTS = 10
QUADTREE_MAX_LEVELS = 10
QUADTREE_EPSILON = 10

BRANCH_DIRECTION_OFFSET_LIMIT = 5
CURVE_DIRECTION_OFFSET_LIMIT = 15