
EPSILON = 1e-2
STREET_SEGMENT_LENGTH = 400
STREET_SEGMENT_LENGTH_OFFSET_LIMIT = 200

HIGHWAY_SEGMENT_LENGTH = 1000
HIGHWAY_SEGMENT_LENGTH_OFFSET_LIMIT = 200

STREET_SEGMENT_WIDTH = 6
STREET_SEGMENT_WIDTH_OFFSET_LIMIT = 2
HIGHWAY_SEGMENT_WIDTH = 10

STREET_BRANCH_PROBABILITY = 0.6
STREET_BRANCH_RIGHT_PROBABILITY = 0.5
HIGHWAY_BRANCH_HEAT_THRESHOLD = 0.2
HIGHWAY_BRANCH_RIGHT_PROBABILITY = 0.5

HIGHWAY_DEGENERATE_PROBABILITY = 0.8

NORMAL_BRANCH_POPULATION_THRESHOLD = 0.1
BRANCH_TIME_DELAY_HIGHWAY = 5
BRANCH_TIME_DELAY_STREET = 0
MINIMUM_INTERSECTION_DEVIATION = 30 # degrees
SEGMENT_COUNT_LIMIT = 1000
DEBUG_DELAY = 0 # ms
ROAD_SNAP_DISTANCE = 50
HEAT_MAP_PIXEL_DIM = 50 # px

QUADTREE_PARAMS_X = -20000
QUADTREE_PARAMS_Y = -20000
QUADTREE_PARAMS_W = -40000
QUADTREE_PARAMS_H = -40000

QUADTREE_MAX_OBJECTS = 10
QUADTREE_MAX_LEVELS = 10
QUADTREE_EPSILON = 10

HIGHWAY_BRANCH_DIRECTION_OFFSET_LIMIT = 5
STREET_BRANCH_DIRECTION_OFFSET_LIMIT = 10
HIGHWAY_CURVE_DIRECTION_OFFSET_LIMIT = 5
STREET_CURVE_DIRECTION_OFFSET_LIMIT = 5